---
name: Path-Abstract
version: 0.080
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
abstract: A fast and featureful class for UNIX-style path manipulation
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Scalar::Util: 0
  Sub::Exporter: 0
build_requires:
  Scalar::Util: 0
  Test::Lazy: 0
  Test::More: 0
provides:
  Path::Abstract:
    file: lib/Path/Abstract.pm
    version: 0.080
  Path::Abstract::Fast:
    file: lib/Path/Abstract/Fast.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
